/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Interfaces.Empleados;
import Logica.Logica_Empelados;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Luis Angel
 */
public class Formulario_Empleados extends javax.swing.JFrame {

    private Logica_Empelados LEMPLEADOS;

    public Formulario_Empleados() {
        initComponents();
        LEMPLEADOS = new Logica_Empelados();
        this.setLocationRelativeTo(null);
        listado();

    }

    private void listado() {
        /**
         * Metodo encargado de insertar los datos obtenidos del metodo
         * obtenerDatos() de la clase Logica_Empleados.
         */
        jt_Datos.setModel(LEMPLEADOS.obtenerDatos());
    }

    private void limpiar() {
        /**
         * Metodo encargado de setear todos los campos con texto a sin texto.
         */
        jtf_id.setText("");
        jtf_nombre.setText("");
        jtf_apellido.setText("");
        jtf_calle.setText("");
        jtf_colonia.setText("");
        jtf_telefono.setText("");
        jtf_rfc.setText("");
        jtf_imss.setText("");
        jtf_curp.setText("");
        jtf_departamento.setText("");
        jtf_nombre.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtf_nombre = new javax.swing.JTextField();
        jtf_apellido = new javax.swing.JTextField();
        jtf_calle = new javax.swing.JTextField();
        jtf_telefono = new javax.swing.JTextField();
        jtf_rfc = new javax.swing.JTextField();
        jtf_imss = new javax.swing.JTextField();
        jtf_curp = new javax.swing.JTextField();
        jtf_departamento = new javax.swing.JTextField();
        jcb_puesto = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jtf_id = new javax.swing.JTextField();
        jlb_Foto = new javax.swing.JLabel();
        dcb_ingreso = new datechooser.beans.DateChooserCombo();
        jtf_colonia = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jl_Ruta = new javax.swing.JLabel();
        btn_borrar = new javax.swing.JLabel();
        jcb_Opciones = new javax.swing.JComboBox<>();
        jt_Busqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_Datos = new javax.swing.JTable();
        btn_atras = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JLabel();
        btn_salir4 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Nombre");

        jLabel4.setText("Apellido");

        jLabel5.setText("Calle");

        jLabel6.setText("Telefono");

        jLabel7.setText("RFC");

        jLabel8.setText("IMSS");

        jLabel9.setText("Curp");

        jLabel10.setText("Puesto");

        jLabel11.setText("Departamento");

        jLabel12.setText("Fecha de ingreso");

        jtf_nombre.setToolTipText("asd");

        jtf_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_telefonoActionPerformed(evt);
            }
        });
        jtf_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_telefonoKeyTyped(evt);
            }
        });

        jcb_puesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guardia", "Administración", "Operación" }));

        jLabel15.setText("Id");

        jtf_id.setEditable(false);

        jlb_Foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AgregarImagen.png"))); // NOI18N
        jlb_Foto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlb_FotoMouseClicked(evt);
            }
        });

        jLabel13.setText("Colonia");

        btn_borrar.setFont(new java.awt.Font("Montserrat Light", 1, 24)); // NOI18N
        btn_borrar.setForeground(new java.awt.Color(43, 58, 100));
        btn_borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton_Actualizar.png"))); // NOI18N
        btn_borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_borrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_borrarMouseEntered(evt);
            }
        });

        jcb_Opciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "NOMBRE", "APELLIDO", "CALLE", "COLONIA", "PUESTO" }));

        jt_Busqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jt_BusquedaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel15)
                    .addComponent(jLabel13)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_calle, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtf_apellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                .addComponent(jtf_nombre, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jtf_colonia, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(127, 127, 127)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dcb_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcb_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_imss, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_curp, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(jlb_Foto)
                        .addGap(109, 109, 109))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtf_rfc, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 473, Short.MAX_VALUE)
                        .addComponent(jl_Ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcb_Opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jt_Busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_borrar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jtf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jtf_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtf_calle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_colonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_rfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jtf_imss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jtf_curp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jcb_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jtf_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(dcb_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jlb_Foto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(jl_Ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcb_Opciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jt_Busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 890, 320));

        jt_Datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jt_Datos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_DatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_Datos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 890, 170));

        btn_atras.setFont(new java.awt.Font("Montserrat Light", 1, 24)); // NOI18N
        btn_atras.setForeground(new java.awt.Color(43, 58, 100));
        btn_atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton_Atras.png"))); // NOI18N
        btn_atras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_atrasMouseClicked(evt);
            }
        });
        getContentPane().add(btn_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, -1, 30));

        btn_guardar.setFont(new java.awt.Font("Montserrat Light", 1, 24)); // NOI18N
        btn_guardar.setForeground(new java.awt.Color(43, 58, 100));
        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton_Guardar.png"))); // NOI18N
        btn_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guardarMouseClicked(evt);
            }
        });
        getContentPane().add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 590, -1, 30));

        btn_salir4.setFont(new java.awt.Font("Montserrat Light", 1, 24)); // NOI18N
        btn_salir4.setForeground(new java.awt.Color(43, 58, 100));
        btn_salir4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton_Salir.png"))); // NOI18N
        btn_salir4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_salir4MouseClicked(evt);
            }
        });
        getContentPane().add(btn_salir4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 590, -1, 30));

        fondo.setFont(new java.awt.Font("Montserrat Light", 1, 48)); // NOI18N
        fondo.setForeground(new java.awt.Color(255, 255, 255));
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RegistroEmpleados.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jt_DatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_DatosMouseClicked
        // TODO add your handling code here:
        int fila = jt_Datos.getSelectedRow(); //Variable int para obtener la fila seleccionada
        jtf_id.setText(jt_Datos.getValueAt(fila, 0).toString()); //Setemaos el valor de la fila seleccionada en la columna 0
        jtf_nombre.setText(jt_Datos.getValueAt(fila, 1).toString()); //Setemaos el valor de la fila seleccionada en la columna 0
        jtf_apellido.setText(jt_Datos.getValueAt(fila, 2).toString()); //Setemaos el valor de la fila seleccionada en la columna 0
        jtf_calle.setText(jt_Datos.getValueAt(fila, 3).toString()); //Setemaos el valor de la fila seleccionada en la columna 0
        jtf_colonia.setText(jt_Datos.getValueAt(fila, 4).toString()); //Setemaos el valor de la fila seleccionada en la columna 0
        jtf_telefono.setText(jt_Datos.getValueAt(fila, 5).toString()); //Setemaos el valor de la fila seleccionada en la columna 0
        jtf_rfc.setText(jt_Datos.getValueAt(fila, 6).toString()); //Setemaos el valor de la fila seleccionada en la columna 0
        jtf_imss.setText(jt_Datos.getValueAt(fila, 7).toString()); //Setemaos el valor de la fila seleccionada en la columna 0
        jtf_curp.setText(jt_Datos.getValueAt(fila, 8).toString()); //Setemaos el valor de la fila seleccionada en la columna 0
        jtf_departamento.setText(jt_Datos.getValueAt(fila, 10).toString()); //Setemaos el valor de la fila seleccionada en la columna 0
        dcb_ingreso.setText(jt_Datos.getValueAt(fila, 11).toString()); //Setemaos el valor de la fila seleccionada en la columna 0

    }//GEN-LAST:event_jt_DatosMouseClicked

    private void jtf_telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_telefonoKeyTyped
        // TODO add your handling code here:
        int limite = 10;

        if (jtf_telefono.getText()
                .length() == limite) {
            evt.consume();
        }
    }//GEN-LAST:event_jtf_telefonoKeyTyped

    private void jtf_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_telefonoActionPerformed

    private void jlb_FotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlb_FotoMouseClicked
        // TODO add your handling code here:
        JFileChooser archivos = new JFileChooser();
        int ventana = archivos.showOpenDialog(null);
        if (ventana == JFileChooser.APPROVE_OPTION) {
            File archivo = archivos.getSelectedFile();
            jl_Ruta.setText(String.valueOf(archivo));
            Image foto_perfil = getToolkit().getImage(jl_Ruta.getText());
            foto_perfil = foto_perfil.getScaledInstance(130, 130, Image.SCALE_DEFAULT);
            jlb_Foto.setIcon(new ImageIcon(foto_perfil));
        }
    }//GEN-LAST:event_jlb_FotoMouseClicked

    private void btn_atrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_atrasMouseClicked
        // TODO add your handling code here:
        Empleados EMP = new Empleados();
        this.setVisible(false);
        dispose();
        EMP.setVisible(true);
    }//GEN-LAST:event_btn_atrasMouseClicked

    private void btn_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarMouseClicked
        // TODO add your handling code here:

        // Obtiene los datos obtenidos del formulario.
        String nombre = jtf_nombre.getText();
        String apellido = jtf_apellido.getText();
        String calle = jtf_calle.getText();
        String colonia = jtf_calle.getText();
        String telefono = jtf_telefono.getText();
        String rfc = jtf_rfc.getText();
        String imss = jtf_imss.getText();
        String curp = jtf_curp.getText();
        String puesto = jcb_puesto.getSelectedItem().toString();
        String departamento = jtf_departamento.getText();
        String ingreso = dcb_ingreso.getText();
        String imagen = jl_Ruta.getText();

        int res;

        try {
            res = LEMPLEADOS.insertarDatos(nombre, apellido, calle, colonia, telefono, rfc, imss, curp, puesto, departamento, ingreso, imagen);
            /**
             * Inserta los datos obtenidos del formulario en la base de
             * datos.Res regresa un valo entero al insertar un campo.
             */
            /**
             * Cuando res regresa un valor mayor a 0 actulizamos nuestra tabla.
             */
            if (res > 0) {
                listado(); //Llama la funcion para mostrar los datos
                limpiar(); //Llama la funcion limpiar los datos
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Formulario_Empleados.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btn_guardarMouseClicked

    private void btn_salir4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salir4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_salir4MouseClicked

    private void btn_borrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_borrarMouseClicked
        // TODO add your handling code here:
        int res;
        String id = jtf_id.getText();
        String nombre = jtf_nombre.getText();
        String apellido = jtf_apellido.getText();
        String calle = jtf_calle.getText();
        String colonia = jtf_calle.getText();
        String telefono = jtf_telefono.getText();
        String rfc = jtf_rfc.getText();
        String imss = jtf_imss.getText();
        String curp = jtf_curp.getText();
        String puesto = jcb_puesto.getSelectedItem().toString();
        String departamento = jtf_departamento.getText();
        String ingreso = dcb_ingreso.getText();

        res = LEMPLEADOS.actualizarDatos(id, nombre, apellido, calle, colonia, telefono, rfc, imss, curp, puesto, departamento, ingreso);
        if (res > 0) {
            listado(); //Llama la funcion para mostrar los datos
            limpiar(); //Llama la funcion limpiar los datos
        }
    }//GEN-LAST:event_btn_borrarMouseClicked

    private void btn_borrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_borrarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_borrarMouseEntered

    private void jt_BusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_BusquedaKeyReleased
        // TODO add your handling code here:
        char tecla = evt.getKeyChar();
        if (tecla == KeyEvent.VK_ENTER) {
            jt_Datos.setModel(LEMPLEADOS.buscarDatos(jcb_Opciones.getSelectedIndex(), jt_Busqueda.getText()));
        }
    }//GEN-LAST:event_jt_BusquedaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario_Empleados.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario_Empleados.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario_Empleados.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario_Empleados.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario_Empleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_atras;
    private javax.swing.JLabel btn_borrar;
    private javax.swing.JLabel btn_guardar;
    private javax.swing.JLabel btn_salir4;
    private datechooser.beans.DateChooserCombo dcb_ingreso;
    private javax.swing.JLabel fondo;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcb_Opciones;
    private javax.swing.JComboBox<String> jcb_puesto;
    private javax.swing.JLabel jl_Ruta;
    private javax.swing.JLabel jlb_Foto;
    private javax.swing.JTextField jt_Busqueda;
    private javax.swing.JTable jt_Datos;
    private javax.swing.JTextField jtf_apellido;
    private javax.swing.JTextField jtf_calle;
    private javax.swing.JTextField jtf_colonia;
    private javax.swing.JTextField jtf_curp;
    private javax.swing.JTextField jtf_departamento;
    private javax.swing.JTextField jtf_id;
    private javax.swing.JTextField jtf_imss;
    private javax.swing.JTextField jtf_nombre;
    private javax.swing.JTextField jtf_rfc;
    private javax.swing.JTextField jtf_telefono;
    // End of variables declaration//GEN-END:variables
}
