/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Logica.Logica_Asistencia;

/**
 *
 * @author Luis Angel
 */
public class Visualizar_Asitencia extends javax.swing.JFrame {

    private Logica_Asistencia LASISTECIA;

    /**
     * Creates new form Formulario_Asistencia
     */
    public Visualizar_Asitencia() {
        initComponents();

        LASISTECIA = new Logica_Asistencia();
        this.setLocationRelativeTo(null);
        listado();
    }

    private void listado() {
        /**
         * Metodo encargado de insertar los datos obtenidos del metodo
         * obtenerDatos() de la clase Logica_Empleados.
         */
        jt_Datos.setModel(LASISTECIA.obtenerDatosVisualizar());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtf_nombre = new javax.swing.JTextField();
        jtf_apellido = new javax.swing.JTextField();
        jtf_puesto = new javax.swing.JTextField();
        jtf_lugar_trabajo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtf_id = new javax.swing.JTextField();
        jlb_Foto = new javax.swing.JLabel();
        jlb_Ruta = new javax.swing.JLabel();
        dcb_fecha = new datechooser.beans.DateChooserCombo();
        jtf_observacion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_Datos = new javax.swing.JTable();
        jb_guardar = new javax.swing.JButton();
        jb_canselar = new javax.swing.JButton();
        btn_atras = new javax.swing.JLabel();
        btn_salir4 = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Nombre");

        jLabel4.setText("Apellido");

        jLabel10.setText("Puesto");

        jLabel11.setText("Lugar de trabajo");

        jLabel12.setText("Fecha de asistencia");

        jtf_nombre.setEditable(false);
        jtf_nombre.setToolTipText("asd");

        jtf_apellido.setEditable(false);

        jtf_puesto.setEditable(false);

        jLabel14.setText("Observacion");

        jLabel15.setText("Id");

        jtf_id.setEditable(false);

        jlb_Foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/perfil_100.png"))); // NOI18N
        jlb_Foto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlb_FotoMouseClicked(evt);
            }
        });

        jlb_Ruta.setText("Imagen");

        dcb_fecha.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(28, 28, 28)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jLabel14)
                .addComponent(jLabel15)
                .addComponent(jLabel3)
                .addComponent(jLabel4)
                .addComponent(jLabel10)
                .addComponent(jLabel11)
                .addComponent(jLabel12))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jtf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(dcb_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jtf_nombre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_puesto, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_apellido, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_lugar_trabajo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                .addComponent(jtf_observacion, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jlb_Ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jlb_Foto))
            .addGap(219, 219, 219))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jtf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtf_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtf_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jtf_lugar_trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jlb_Foto))
                .addComponent(jlb_Ruta))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jLabel12)
                .addComponent(dcb_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel14)
                .addComponent(jtf_observacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(22, Short.MAX_VALUE))
    );

    getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 890, -1));

    jt_Datos.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {

        }
    ));
    jt_Datos.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jt_DatosMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(jt_Datos);

    getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 890, 141));

    jb_guardar.setText("Guardar Asistencia");
    jb_guardar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jb_guardarActionPerformed(evt);
        }
    });
    getContentPane().add(jb_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 514, -1, -1));

    jb_canselar.setText("Cancelar");
    jb_canselar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jb_canselarActionPerformed(evt);
        }
    });
    getContentPane().add(jb_canselar, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 514, -1, -1));

    btn_atras.setFont(new java.awt.Font("Montserrat Light", 1, 24)); // NOI18N
    btn_atras.setForeground(new java.awt.Color(43, 58, 100));
    btn_atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton_Atras.png"))); // NOI18N
    btn_atras.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            btn_atrasMouseClicked(evt);
        }
    });
    getContentPane().add(btn_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, -1, 30));

    btn_salir4.setFont(new java.awt.Font("Montserrat Light", 1, 24)); // NOI18N
    btn_salir4.setForeground(new java.awt.Color(43, 58, 100));
    btn_salir4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton_Salir.png"))); // NOI18N
    btn_salir4.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            btn_salir4MouseClicked(evt);
        }
    });
    getContentPane().add(btn_salir4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 590, -1, 30));

    btn_guardar.setFont(new java.awt.Font("Montserrat Light", 1, 24)); // NOI18N
    btn_guardar.setForeground(new java.awt.Color(43, 58, 100));
    btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton_Guardar.png"))); // NOI18N
    btn_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            btn_guardarMouseClicked(evt);
        }
    });
    getContentPane().add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 590, -1, 30));

    fondo.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
    fondo.setForeground(new java.awt.Color(255, 255, 255));
    fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AsistenciaEmpleados.png"))); // NOI18N
    getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, -1));

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlb_FotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlb_FotoMouseClicked
        // TODO add your handling code here:
//        JFileChooser archivos = new JFileChooser();
//        int ventana = archivos.showOpenDialog(null);
//        if (ventana == JFileChooser.APPROVE_OPTION) {
//            File fila = archivos.getSelectedFile();
//
//        }
    }//GEN-LAST:event_jlb_FotoMouseClicked

    private void jt_DatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_DatosMouseClicked
        // TODO add your handling code here:
        int fila = jt_Datos.getSelectedRow(); //Variable int para obtener la fila seleccionada
        jtf_id.setText(jt_Datos.getValueAt(fila, 0).toString()); //Setemaos el valor de la fila seleccionada en la columna 0
        jtf_nombre.setText(jt_Datos.getValueAt(fila, 1).toString()); //Setemaos el valor de la fila seleccionada en la columna 1
        jtf_apellido.setText(jt_Datos.getValueAt(fila, 2).toString()); //Setemaos el valor de la fila seleccionada en la columna 1
        jtf_puesto.setText(jt_Datos.getValueAt(fila, 3).toString()); //Setemaos el valor de la fila seleccionada en la columna 1
    }//GEN-LAST:event_jt_DatosMouseClicked

    private void jb_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_guardarActionPerformed

        // Obtiene los datos obtenidos del formulario.
        String id_empleado = jtf_id.getText();
        String nombre = jtf_nombre.getText();
        String apellido = jtf_apellido.getText();
        String puesto = jtf_puesto.getText();
        String lugar_trabajo = jtf_lugar_trabajo.getText();
        String fecha = dcb_fecha.getText();
        String observacion = jtf_observacion.getText();

   
        //        InputStream imagen = jlb_Foto.getText();

        /**
        * Inserta los datos obtenidos del formulario en la base de datos.Res
        * regresa un valo entero al insertar un campo.
        */
        int res = LASISTECIA.insertarAsitencia(id_empleado, nombre, apellido, puesto, lugar_trabajo, fecha, observacion);

        /**
        * Cuando res regresa un valor mayor a 0 actulizamos nuestra tabla.
        */
        if (res > 0) {
          //  listado(); //Llama la funcion para mostrar los datos
         //   limpiar(); //Llama la funcion limpiar los datos
        }

    }//GEN-LAST:event_jb_guardarActionPerformed

    private void jb_canselarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_canselarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_canselarActionPerformed

    private void btn_atrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_atrasMouseClicked
        // TODO add your handling code here:
//        Empleados EMP = new Empleados();
//        this.setVisible(false);
//        dispose();
//        EMP.setVisible(true);
    }//GEN-LAST:event_btn_atrasMouseClicked

    private void btn_salir4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salir4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_salir4MouseClicked

    private void btn_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarMouseClicked
        // TODO add your handling code here:

//        // Obtiene los datos obtenidos del formulario.
//        String nombre = jtf_nombre.getText();
//        String apellido = jtf_apellido.getText();
//        String calle = jtf_calle.getText();
//        String colonia = jtf_calle.getText();
//        String telefono = jtf_telefono.getText();
//        String rfc = jtf_rfc.getText();
//        String imss = jtf_imss.getText();
//        String curp = jtf_curp.getText();
//        String puesto = jcb_puesto.getSelectedItem().toString();
//        String departamento = jtf_departamento.getText();
//        String ingreso = dcb_ingreso.getText();
//
//        String datos = jlb_Foto.getText();
//        //        InputStream imagen = jlb_Foto.getText();
//
//        /**
//        * Inserta los datos obtenidos del formulario en la base de datos.Res
//        * regresa un valo entero al insertar un campo.
//        */
//        int res = LEMPLEADOS.insertarDatos(nombre, apellido, calle, colonia, telefono, rfc, imss, curp, puesto, departamento, ingreso);
//
//        /**
//        * Cuando res regresa un valor mayor a 0 actulizamos nuestra tabla.
//        */
//        if (res > 0) {
//            listado(); //Llama la funcion para mostrar los datos
//            limpiar(); //Llama la funcion limpiar los datos
//        }
    }//GEN-LAST:event_btn_guardarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visualizar_Asitencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visualizar_Asitencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visualizar_Asitencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visualizar_Asitencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visualizar_Asitencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_atras;
    private javax.swing.JLabel btn_guardar;
    private javax.swing.JLabel btn_salir4;
    private datechooser.beans.DateChooserCombo dcb_fecha;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_canselar;
    private javax.swing.JButton jb_guardar;
    private javax.swing.JLabel jlb_Foto;
    private javax.swing.JLabel jlb_Ruta;
    private javax.swing.JTable jt_Datos;
    private javax.swing.JTextField jtf_apellido;
    private javax.swing.JTextField jtf_id;
    private javax.swing.JTextField jtf_lugar_trabajo;
    private javax.swing.JTextField jtf_nombre;
    private javax.swing.JTextField jtf_observacion;
    private javax.swing.JTextField jtf_puesto;
    // End of variables declaration//GEN-END:variables

}
