/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Formularios.Formulario_Asistencia;
import Formularios.Formulario_Cientes;
import Formularios.Formulario_Empleados;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Luis Angel
 */
public class Empleados extends javax.swing.JFrame {

    /**
     * Creates new form Empleados
     */
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/perfil_100.png"));
        return retValue;
    }

    public Empleados() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jl_Asistencia = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jl_Registro = new javax.swing.JLabel();
        btn_salir = new javax.swing.JLabel();
        btn_salir1 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Montserrat Light", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(43, 58, 100));
        jLabel3.setText("Registro");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, -1, 40));

        jl_Asistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Asistencia.png"))); // NOI18N
        jl_Asistencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_AsistenciaMouseClicked(evt);
            }
        });
        getContentPane().add(jl_Asistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, -1, -1));

        jLabel2.setFont(new java.awt.Font("Montserrat Light", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(43, 58, 100));
        jLabel2.setText("Asistencia");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, -1, -1));

        jl_Registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registro.png"))); // NOI18N
        jl_Registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_RegistroMouseClicked(evt);
            }
        });
        getContentPane().add(jl_Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, -1, -1));

        btn_salir.setFont(new java.awt.Font("Montserrat Light", 1, 24)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(43, 58, 100));
        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton_Atras.png"))); // NOI18N
        btn_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_salirMouseClicked(evt);
            }
        });
        getContentPane().add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 580, -1, 30));

        btn_salir1.setFont(new java.awt.Font("Montserrat Light", 1, 24)); // NOI18N
        btn_salir1.setForeground(new java.awt.Color(43, 58, 100));
        btn_salir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton_Salir.png"))); // NOI18N
        btn_salir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_salir1MouseClicked(evt);
            }
        });
        getContentPane().add(btn_salir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 580, -1, 30));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Empleados.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jl_RegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_RegistroMouseClicked
        // TODO add your handling code here:
        Formulario_Empleados FORM_EMP = new Formulario_Empleados();
        this.setVisible(false);
        dispose();
        FORM_EMP.setVisible(true);

    }//GEN-LAST:event_jl_RegistroMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
//        Formulario_Empleados FORM_EMP = new Formulario_Empleados();
//        this.setVisible(false);
//        dispose();
//        FORM_EMP.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btn_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseClicked
        // TODO add your handling code here:
        Pantalla_Principal PANT_PRIN = new Pantalla_Principal();
        this.setVisible(false);
        dispose();
        PANT_PRIN.setVisible(true);

    }//GEN-LAST:event_btn_salirMouseClicked

    private void btn_salir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salir1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_salir1MouseClicked

    private void jl_AsistenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_AsistenciaMouseClicked
        // TODO add your handling code here:
        Formulario_Asistencia FORM_ASIS = new Formulario_Asistencia();
        this.setVisible(false);
        dispose();
        FORM_ASIS.setVisible(true);
    }//GEN-LAST:event_jl_AsistenciaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel btn_salir;
    private javax.swing.JLabel btn_salir1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jl_Asistencia;
    private javax.swing.JLabel jl_Registro;
    // End of variables declaration//GEN-END:variables
}
