/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Formularios.Formulario_Cientes;
import Formularios.Formulario_Empleados;
import Formularios.Formulario_Nomina;

/**
 *
 * @author Luis Angel
 */
public class Pantalla_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla_Principal
     */
    public Pantalla_Principal() {
        initComponents();

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Nomina = new javax.swing.JLabel();
        jl_Nomina2 = new javax.swing.JLabel();
        jl_Empleado2 = new javax.swing.JLabel();
        jl_Empleado = new javax.swing.JLabel();
        jl_Cliente = new javax.swing.JLabel();
        jl_Salir = new javax.swing.JLabel();
        jl_Cliente2 = new javax.swing.JLabel();
        jl_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_Nomina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nomina.png"))); // NOI18N
        jl_Nomina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_NominaMouseClicked(evt);
            }
        });
        getContentPane().add(jl_Nomina, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, -1));

        jl_Nomina2.setFont(new java.awt.Font("Montserrat Light", 1, 24)); // NOI18N
        jl_Nomina2.setForeground(new java.awt.Color(43, 58, 100));
        jl_Nomina2.setText("Nomina");
        getContentPane().add(jl_Nomina2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, -1, -1));

        jl_Empleado2.setFont(new java.awt.Font("Montserrat Light", 1, 24)); // NOI18N
        jl_Empleado2.setForeground(new java.awt.Color(43, 58, 100));
        jl_Empleado2.setText("Empleado");
        jl_Empleado2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_Empleado2MouseClicked(evt);
            }
        });
        getContentPane().add(jl_Empleado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, -1, -1));

        jl_Empleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardia2.png"))); // NOI18N
        jl_Empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_EmpleadoMouseClicked(evt);
            }
        });
        getContentPane().add(jl_Empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        jl_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cliente2.png"))); // NOI18N
        jl_Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_ClienteMouseClicked(evt);
            }
        });
        getContentPane().add(jl_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, -1, -1));

        jl_Salir.setFont(new java.awt.Font("Montserrat Light", 1, 24)); // NOI18N
        jl_Salir.setForeground(new java.awt.Color(43, 58, 100));
        jl_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton_Salir.png"))); // NOI18N
        jl_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_SalirMouseClicked(evt);
            }
        });
        getContentPane().add(jl_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 580, -1, 30));

        jl_Cliente2.setFont(new java.awt.Font("Montserrat Light", 1, 24)); // NOI18N
        jl_Cliente2.setForeground(new java.awt.Color(43, 58, 100));
        jl_Cliente2.setText("Cliente");
        jl_Cliente2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_Cliente2MouseClicked(evt);
            }
        });
        getContentPane().add(jl_Cliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, -1, -1));

        jl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pantall_Principal.png"))); // NOI18N
        getContentPane().add(jl_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jl_EmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_EmpleadoMouseClicked
        // TODO add your handling code here:
        Empleados EMP = new Empleados();
        this.setVisible(false);
        dispose();
        EMP.setVisible(true);


    }//GEN-LAST:event_jl_EmpleadoMouseClicked

    private void jl_Empleado2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_Empleado2MouseClicked
        // TODO add your handling code here:
        Formulario_Empleados FORM_EMP = new Formulario_Empleados();
        this.setVisible(false);
        dispose();
        FORM_EMP.setVisible(true);
    }//GEN-LAST:event_jl_Empleado2MouseClicked

    private void jl_ClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_ClienteMouseClicked
        // TODO add your handling code here:
        Formulario_Cientes FORM_CLI = new Formulario_Cientes();
        this.setVisible(false);
        dispose();
        FORM_CLI.setVisible(true);
    }//GEN-LAST:event_jl_ClienteMouseClicked

    private void jl_Cliente2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_Cliente2MouseClicked
        // TODO add your handling code here:
        Formulario_Cientes FORM_CLI = new Formulario_Cientes();
        this.setVisible(false);
        dispose();
        FORM_CLI.setVisible(true);
    }//GEN-LAST:event_jl_Cliente2MouseClicked

    private void jl_SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_SalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jl_SalirMouseClicked

    private void jl_NominaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_NominaMouseClicked
        // TODO add your handling code here:
        Formulario_Nomina FORM_NOMINA = new Formulario_Nomina();
        this.setVisible(false);
        dispose();
        FORM_NOMINA.setVisible(true);
    }//GEN-LAST:event_jl_NominaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jl_Cliente;
    private javax.swing.JLabel jl_Cliente2;
    private javax.swing.JLabel jl_Empleado;
    private javax.swing.JLabel jl_Empleado2;
    private javax.swing.JLabel jl_Nomina;
    private javax.swing.JLabel jl_Nomina2;
    private javax.swing.JLabel jl_Salir;
    private javax.swing.JLabel jl_fondo;
    // End of variables declaration//GEN-END:variables
}
