/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Logica.Logica_Registro;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Luis Angel
 */
public class Registro extends javax.swing.JFrame {

    private Logica_Registro LREGISTRO;
    Image img;

    /**
     * Creates new form Principal
     */
    public Registro() {
        initComponents();
        LREGISTRO = new Logica_Registro();
        //Usuario administrador
        //Usuario contrasena
        //INSERT INTO `registro` (`id`, `usuario`, `contrasena`) VALUES ('1', 'administrador', SHA1('contrasena'))
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtf_usuario = new javax.swing.JTextField();
        jtf_contrasena = new javax.swing.JPasswordField();
        jtf_ingresar = new javax.swing.JLabel();
        jtf_salir = new javax.swing.JLabel();
        jl_Fonodo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jtf_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 300, -1));
        getContentPane().add(jtf_contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 300, 20));

        jtf_ingresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton_Ingresar.png"))); // NOI18N
        jtf_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtf_ingresarMouseClicked(evt);
            }
        });
        getContentPane().add(jtf_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 590, -1, -1));

        jtf_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton_Salir.png"))); // NOI18N
        jtf_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtf_salirMouseClicked(evt);
            }
        });
        getContentPane().add(jtf_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 590, -1, -1));

        jl_Fonodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Inicio.png"))); // NOI18N
        getContentPane().add(jl_Fonodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtf_ingresarMouseClicked
        // TODO add your handling code here:
        String usuario = jtf_usuario.getText();
        String contrasena = jtf_contrasena.getText();

        Pantalla_Principal pantallaPrin = new Pantalla_Principal();
        int res = LREGISTRO.iniciar(usuario, contrasena);
        if (res > 0) {
            this.setVisible(false);
            dispose();
            pantallaPrin.setVisible(true);

        }
    }//GEN-LAST:event_jtf_ingresarMouseClicked

    private void jtf_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtf_salirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jtf_salirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jl_Fonodo;
    private javax.swing.JPasswordField jtf_contrasena;
    private javax.swing.JLabel jtf_ingresar;
    private javax.swing.JLabel jtf_salir;
    private javax.swing.JTextField jtf_usuario;
    // End of variables declaration//GEN-END:variables
}
